### ISSUE TITLE
cannot reproduce the results in the paper

### ISSUE THREAD

**Issue by sung-won-kim** [SongW-SW/TENT#1]
Hi,

I ran your code without fixing any parameters, but I copied and pasted the dataset file from the official github of GPN. 
I just ran with dblp dataset, but I cannot get the results in the paper.

I attach the training procedures and the result of the test.
would you check these results, and give some advice?

Thank you.

![image](https://user-images.githubusercontent.com/37684658/178186850-844459f8-2682-43e6-a79e-5fd65466be25.png)
![image](https://user-images.githubusercontent.com/37684658/178186866-b9663358-95b1-4426-9a5b-525549e466b2.png)

![image](https://user-images.githubusercontent.com/37684658/178185856-5fb8347e-7742-407f-b3bd-d08ef533309f.png)

**Comment by SongW-SW** [comment]
Hi, thank you for pointing out this. It seems that I had uploaded the wrong (old) version of the training files. I will soon upload a new one that we use currently. The datasets used are partially the same as GPN, and I will also upload the other two datasets. Thank you!

**Comment by SongW-SW** [comment]
Hi Kim, I have uploaded the new version of the code. Sorry for the late reply.

I modified the code thoroughly so that it's more clear and easier to read. Moreover, I uploaded the required three datasets as a zip file, and the ogbn-arxiv dataset will be downloaded automatically. I have tested the code and the results are comparable, while due to the randomness, sometimes it may require multiple runs to reduce the variance. 

Thank you for your feedback and interest in our work!

**Comment by sung-won-kim** [comment]
> Hi Kim, I have uploaded the new version of the code. Sorry for the late reply.
> 
> I modified the code thoroughly so that it's more clear and easier to read. Moreover, I uploaded the required three datasets as a zip file, and the ogbn-arxiv dataset will be downloaded automatically. I have tested the code and the results are comparable, while due to the randomness, sometimes it may require multiple runs to reduce the variance.
> 
> Thank you for your feedback and interest in our work!

Thank you for your reply! 
It would be great help for me. thank you.
